/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author u03808019140
 */
public class JDlgClienteNcc extends javax.swing.JDialog {

    boolean incluir = false;
    private MaskFormatter mascaraDataNasc, mascaraCpf, mascaraTel, mascaraDataCadas, mascaraCep;

    /**
     * Creates new form jDlgCliente
     */
    public JDlgClienteNcc(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastrar cliente");
        setLocationRelativeTo(null);
        try {
            mascaraDataNasc = new MaskFormatter("##/##/####");
            mascaraCpf = new MaskFormatter("###.###.###-##");
            mascaraTel = new MaskFormatter("(##) #####-####");
            mascaraDataCadas = new MaskFormatter("##/##/####");
            mascaraCep = new MaskFormatter("#####-###");
            jFmtDataNascimento.setFormatterFactory(new DefaultFormatterFactory(mascaraDataNasc));
            jFmtCPF.setFormatterFactory(new DefaultFormatterFactory(mascaraCpf));
            jFmtTelefone.setFormatterFactory(new DefaultFormatterFactory(mascaraTel));
            jFmtDataCadastro.setFormatterFactory(new DefaultFormatterFactory(mascaraDataCadas));
            jFmtCEP.setFormatterFactory(new DefaultFormatterFactory(mascaraCep));
        } catch (ParseException ex) {
            Logger.getLogger(JDlgClienteNcc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jFmtRG = new javax.swing.JFormattedTextField();
        jFmtCPF = new javax.swing.JFormattedTextField();
        jFmtTelefone = new javax.swing.JFormattedTextField();
        jTxtRua = new javax.swing.JTextField();
        jFmtCEP = new javax.swing.JFormattedTextField();
        jTxtBairro = new javax.swing.JTextField();
        jTxtCidade = new javax.swing.JTextField();
        jTxtNumero = new javax.swing.JTextField();
        jTxtComplemento = new javax.swing.JTextField();
        jChbAtivo = new javax.swing.JCheckBox();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jFmtEmail = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        jFmtTotalGasto = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jTxtOcupacao = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jFmtDataCadastro = new javax.swing.JFormattedTextField();
        jTxtIdade = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jFmtDataNascimento = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Código");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(6, 6, 33, 14);
        getContentPane().add(jTxtCodigo);
        jTxtCodigo.setBounds(6, 28, 86, 20);

        jLabel2.setText("Nome");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(98, 6, 27, 14);
        getContentPane().add(jTxtNome);
        jTxtNome.setBounds(98, 28, 409, 20);

        jLabel4.setText("CPF");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(350, 60, 19, 14);

        jLabel5.setText("E-mail");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(240, 110, 28, 14);

        jLabel6.setText("Idade");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(123, 56, 28, 14);

        jLabel8.setText("RG");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 110, 14, 14);

        jLabel9.setText("Telefone");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(203, 56, 42, 14);

        jLabel10.setText("CEP");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 170, 19, 14);

        jLabel11.setText("Rua");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(150, 170, 19, 14);

        jLabel12.setText("Bairro");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 220, 28, 14);

        jLabel13.setText("Cidade");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(300, 170, 33, 14);

        jLabel14.setText("Número");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(550, 170, 37, 14);

        jLabel15.setText("Complemento");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(340, 220, 65, 14);

        jLabel16.setText("Ativo");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(590, 280, 25, 14);
        getContentPane().add(jFmtRG);
        jFmtRG.setBounds(10, 130, 220, 20);
        getContentPane().add(jFmtCPF);
        jFmtCPF.setBounds(350, 80, 160, 20);
        getContentPane().add(jFmtTelefone);
        jFmtTelefone.setBounds(199, 78, 146, 20);
        getContentPane().add(jTxtRua);
        jTxtRua.setBounds(140, 190, 140, 20);
        getContentPane().add(jFmtCEP);
        jFmtCEP.setBounds(10, 190, 120, 20);
        getContentPane().add(jTxtBairro);
        jTxtBairro.setBounds(10, 240, 320, 20);
        getContentPane().add(jTxtCidade);
        jTxtCidade.setBounds(290, 190, 230, 20);
        getContentPane().add(jTxtNumero);
        jTxtNumero.setBounds(530, 190, 110, 20);
        getContentPane().add(jTxtComplemento);
        jTxtComplemento.setBounds(340, 240, 300, 20);
        getContentPane().add(jChbAtivo);
        jChbAtivo.setBounds(560, 280, 21, 21);

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons-sem-senha/icons/add.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnIncluir);
        jBtnIncluir.setBounds(10, 310, 81, 25);

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons-sem-senha/icons/editar.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnAlterar);
        jBtnAlterar.setBounds(100, 310, 85, 25);

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons-sem-senha/icons/confirmar.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnConfirmar);
        jBtnConfirmar.setBounds(280, 310, 99, 25);

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons-sem-senha/icons/pesquisa1.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnPesquisar);
        jBtnPesquisar.setBounds(490, 310, 99, 25);

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons-sem-senha/icons/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnCancelar);
        jBtnCancelar.setBounds(390, 310, 95, 25);

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons-sem-senha/icons/excluir.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnExcluir);
        jBtnExcluir.setBounds(190, 310, 83, 25);
        getContentPane().add(jFmtEmail);
        jFmtEmail.setBounds(240, 130, 230, 20);

        jLabel17.setText("Total gasto");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(519, 6, 54, 14);
        getContentPane().add(jFmtTotalGasto);
        jFmtTotalGasto.setBounds(513, 28, 136, 20);

        jLabel7.setText("Ocupação");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(480, 110, 48, 14);
        getContentPane().add(jTxtOcupacao);
        jTxtOcupacao.setBounds(480, 130, 170, 20);

        jLabel18.setText("Data de cadastro");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(513, 56, 83, 14);
        getContentPane().add(jFmtDataCadastro);
        jFmtDataCadastro.setBounds(517, 80, 130, 20);
        getContentPane().add(jTxtIdade);
        jTxtIdade.setBounds(123, 78, 50, 20);

        jLabel19.setText("Data de nascimento");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(6, 56, 95, 14);
        getContentPane().add(jFmtDataNascimento);
        jFmtDataNascimento.setBounds(6, 78, 105, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        incluir = true;
        jTxtCodigo.grabFocus();
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        incluir = false;
        jTxtCodigo.grabFocus();
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
       
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed

    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgClienteNcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgClienteNcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgClienteNcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgClienteNcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgClienteNcc dialog = new JDlgClienteNcc(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JCheckBox jChbAtivo;
    private javax.swing.JFormattedTextField jFmtCEP;
    private javax.swing.JFormattedTextField jFmtCPF;
    private javax.swing.JFormattedTextField jFmtDataCadastro;
    private javax.swing.JFormattedTextField jFmtDataNascimento;
    private javax.swing.JFormattedTextField jFmtEmail;
    private javax.swing.JFormattedTextField jFmtRG;
    private javax.swing.JFormattedTextField jFmtTelefone;
    private javax.swing.JFormattedTextField jFmtTotalGasto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTxtBairro;
    private javax.swing.JTextField jTxtCidade;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtComplemento;
    private javax.swing.JTextField jTxtIdade;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JTextField jTxtNumero;
    private javax.swing.JTextField jTxtOcupacao;
    private javax.swing.JTextField jTxtRua;
    // End of variables declaration//GEN-END:variables
}
