/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Nick
 */
public class JFrmPrincipalNcc extends javax.swing.JFrame {

    /**
     * Creates new form JFrmPrincipal
     */
    public JFrmPrincipalNcc() {
        initComponents();
        setTitle("Página principal");
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        jBtnClienteCadastrar = new javax.swing.JButton();
        jBtnLivroCadastrar = new javax.swing.JButton();
        jBtnVendasMovimento = new javax.swing.JButton();
        jBtnClientesConsultar = new javax.swing.JButton();
        jBtnLivroConsultar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMnuArtista = new javax.swing.JMenuItem();
        jMnuCliente = new javax.swing.JMenuItem();
        jMnuLivro = new javax.swing.JMenuItem();
        jMnuUsuario = new javax.swing.JMenuItem();
        jMnuVendedor = new javax.swing.JMenuItem();
        jMnuSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMnuVendas = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMnuConsultaClientes = new javax.swing.JMenuItem();
        jMnuConsultaVendas = new javax.swing.JMenuItem();
        jMnuConsultaLivros = new javax.swing.JMenuItem();
        jMnuConsultaAutores = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jBtnClienteCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addConta.png"))); // NOI18N
        jBtnClienteCadastrar.setFocusable(false);
        jBtnClienteCadastrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnClienteCadastrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnClienteCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClienteCadastrarActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnClienteCadastrar);

        jBtnLivroCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nota.png"))); // NOI18N
        jBtnLivroCadastrar.setFocusable(false);
        jBtnLivroCadastrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnLivroCadastrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnLivroCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLivroCadastrarActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnLivroCadastrar);

        jBtnVendasMovimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sacola.png"))); // NOI18N
        jBtnVendasMovimento.setFocusable(false);
        jBtnVendasMovimento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnVendasMovimento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnVendasMovimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVendasMovimentoActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnVendasMovimento);

        jBtnClientesConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/contas1.png"))); // NOI18N
        jBtnClientesConsultar.setFocusable(false);
        jBtnClientesConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnClientesConsultar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnClientesConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClientesConsultarActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnClientesConsultar);

        jBtnLivroConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/olho1.png"))); // NOI18N
        jBtnLivroConsultar.setFocusable(false);
        jBtnLivroConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnLivroConsultar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnLivroConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLivroConsultarActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnLivroConsultar);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salvar.png"))); // NOI18N
        jMenu1.setMnemonic('d');
        jMenu1.setText("Cadastrar");

        jMnuArtista.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMnuArtista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addConta.png"))); // NOI18N
        jMnuArtista.setMnemonic('a');
        jMnuArtista.setText("Artista");
        jMnuArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuArtistaActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuArtista);

        jMnuCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMnuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addConta.png"))); // NOI18N
        jMnuCliente.setMnemonic('c');
        jMnuCliente.setText("Cliente");
        jMnuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuCliente);

        jMnuLivro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMnuLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nota.png"))); // NOI18N
        jMnuLivro.setMnemonic('l');
        jMnuLivro.setText("Livro");
        jMnuLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuLivroActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuLivro);

        jMnuUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMnuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario1.png"))); // NOI18N
        jMnuUsuario.setMnemonic('u');
        jMnuUsuario.setText("Usuario");
        jMnuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuUsuario);

        jMnuVendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMnuVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/contas1.png"))); // NOI18N
        jMnuVendedor.setMnemonic('v');
        jMnuVendedor.setText("Vendedor");
        jMnuVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendedorActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuVendedor);

        jMnuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMnuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excluir.png"))); // NOI18N
        jMnuSair.setText("Sair");
        jMnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuSairActionPerformed(evt);
            }
        });
        jMenu1.add(jMnuSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dados2.png"))); // NOI18N
        jMenu2.setMnemonic('m');
        jMenu2.setText("Movimento");

        jMnuVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMnuVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrinho.png"))); // NOI18N
        jMnuVendas.setMnemonic('v');
        jMnuVendas.setText("Vendas");
        jMnuVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendasActionPerformed(evt);
            }
        });
        jMenu2.add(jMnuVendas);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arquivos.png"))); // NOI18N
        jMenu3.setText("Consultas");

        jMnuConsultaClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMnuConsultaClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/contas1.png"))); // NOI18N
        jMnuConsultaClientes.setText("Clientes");
        jMnuConsultaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsultaClientesActionPerformed(evt);
            }
        });
        jMenu3.add(jMnuConsultaClientes);

        jMnuConsultaVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMnuConsultaVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dineiro.png"))); // NOI18N
        jMnuConsultaVendas.setText("Vendas");
        jMnuConsultaVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsultaVendasActionPerformed(evt);
            }
        });
        jMenu3.add(jMnuConsultaVendas);

        jMnuConsultaLivros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMnuConsultaLivros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nota.png"))); // NOI18N
        jMnuConsultaLivros.setText("Livros");
        jMnuConsultaLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsultaLivrosActionPerformed(evt);
            }
        });
        jMenu3.add(jMnuConsultaLivros);

        jMnuConsultaAutores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMnuConsultaAutores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario1.png"))); // NOI18N
        jMnuConsultaAutores.setText("Autores");
        jMnuConsultaAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsultaAutoresActionPerformed(evt);
            }
        });
        jMenu3.add(jMnuConsultaAutores);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuArtistaActionPerformed
        JDlgAutorNcc jDlgArtistaNcc = new JDlgAutorNcc(null, true);
        jDlgArtistaNcc.setVisible(true);
    }//GEN-LAST:event_jMnuArtistaActionPerformed

    private void jMnuLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuLivroActionPerformed
        JDlgLivroNcc jDlgLivroNcc = new JDlgLivroNcc(null, true);
        jDlgLivroNcc.setVisible(true);
    }//GEN-LAST:event_jMnuLivroActionPerformed

    private void jMnuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuClienteActionPerformed
        JDlgClienteNcc jDlgClienteNcc = new JDlgClienteNcc(null, true);
        jDlgClienteNcc.setVisible(true);
    }//GEN-LAST:event_jMnuClienteActionPerformed

    private void jMnuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuarioActionPerformed
        JDlgUsuariosNcc jDlgUsuarioNcc = new JDlgUsuariosNcc(null, true);
        jDlgUsuarioNcc.setVisible(true);
    }//GEN-LAST:event_jMnuUsuarioActionPerformed

    private void jMnuVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendedorActionPerformed
        JDlgVendedorNcc jDlgVendedorNcc = new JDlgVendedorNcc(null, true);
        jDlgVendedorNcc.setVisible(true);
    }//GEN-LAST:event_jMnuVendedorActionPerformed

    private void jMnuVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendasActionPerformed
        JDlgVendasNcc jDlgVendasNcc = new JDlgVendasNcc(null, true);
        jDlgVendasNcc.setVisible(true);
    }//GEN-LAST:event_jMnuVendasActionPerformed

    private void jMnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMnuSairActionPerformed

    private void jMnuConsultaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsultaClientesActionPerformed
        JDlgConsultaClienteNcc jDlgConsultaClienteNcc = new JDlgConsultaClienteNcc(null, true);
        jDlgConsultaClienteNcc.setVisible(true);
    }//GEN-LAST:event_jMnuConsultaClientesActionPerformed

    private void jMnuConsultaVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsultaVendasActionPerformed
        JDlgConsultaVendasNcc jDlgConsultaVendasNcc = new JDlgConsultaVendasNcc(null, true);
        jDlgConsultaVendasNcc.setVisible(true);
    }//GEN-LAST:event_jMnuConsultaVendasActionPerformed

    private void jBtnClienteCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClienteCadastrarActionPerformed
        JDlgClienteNcc jDlgClienteNcc = new JDlgClienteNcc(null, true);
        jDlgClienteNcc.setVisible(true);
    }//GEN-LAST:event_jBtnClienteCadastrarActionPerformed

    private void jMnuConsultaLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsultaLivrosActionPerformed
        JDlgConsultaLivroNcc jDlgConsultaLivroNcc = new JDlgConsultaLivroNcc(null, true);
        jDlgConsultaLivroNcc.setVisible(true);
    }//GEN-LAST:event_jMnuConsultaLivrosActionPerformed

    private void jMnuConsultaAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsultaAutoresActionPerformed
        JDlgConsultaAutorNcc jDlgConsultaAutorNcc = new JDlgConsultaAutorNcc(null, true);
        jDlgConsultaAutorNcc.setVisible(true);
    }//GEN-LAST:event_jMnuConsultaAutoresActionPerformed

    private void jBtnLivroCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLivroCadastrarActionPerformed
        JDlgLivroNcc jDlgLivroNcc = new JDlgLivroNcc(null, true);
        jDlgLivroNcc.setVisible(true);
    }//GEN-LAST:event_jBtnLivroCadastrarActionPerformed

    private void jBtnVendasMovimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVendasMovimentoActionPerformed
        JDlgVendasNcc jDlgVendasNcc = new JDlgVendasNcc(null, true);
        jDlgVendasNcc.setVisible(true);
    }//GEN-LAST:event_jBtnVendasMovimentoActionPerformed

    private void jBtnClientesConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClientesConsultarActionPerformed
        JDlgConsultaClienteNcc jDlgConsultaClienteNcc = new JDlgConsultaClienteNcc(null, true);
        jDlgConsultaClienteNcc.setVisible(true);
    }//GEN-LAST:event_jBtnClientesConsultarActionPerformed

    private void jBtnLivroConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLivroConsultarActionPerformed
        JDlgConsultaLivroNcc jDlgConsultaLivroNcc = new JDlgConsultaLivroNcc(null, true);
        jDlgConsultaLivroNcc.setVisible(true);
    }//GEN-LAST:event_jBtnLivroConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipalNcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipalNcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipalNcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipalNcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmPrincipalNcc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnClienteCadastrar;
    private javax.swing.JButton jBtnClientesConsultar;
    private javax.swing.JButton jBtnLivroCadastrar;
    private javax.swing.JButton jBtnLivroConsultar;
    private javax.swing.JButton jBtnVendasMovimento;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMnuArtista;
    private javax.swing.JMenuItem jMnuCliente;
    private javax.swing.JMenuItem jMnuConsultaAutores;
    private javax.swing.JMenuItem jMnuConsultaClientes;
    private javax.swing.JMenuItem jMnuConsultaLivros;
    private javax.swing.JMenuItem jMnuConsultaVendas;
    private javax.swing.JMenuItem jMnuLivro;
    private javax.swing.JMenuItem jMnuSair;
    private javax.swing.JMenuItem jMnuUsuario;
    private javax.swing.JMenuItem jMnuVendas;
    private javax.swing.JMenuItem jMnuVendedor;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
