package bean;
// Generated 26/09/2025 15:05:32 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AutorNcc generated by hbm2java
 */
@Entity
@Table(name="autorNcc"
    ,catalog="db_nicole_comelli"
)
public class AutorNcc  implements java.io.Serializable {


     private int idAutorNcc;
     private String nomeNcc;
     private String pseudonimoNcc;
     private String nacionalidadeNcc;
     private Date dataNascimentoNcc;
     private String emailNcc;
     private Date dataObitoNcc;

    public AutorNcc() {
    }

	
    public AutorNcc(int idAutorNcc) {
        this.idAutorNcc = idAutorNcc;
    }
    public AutorNcc(int idAutorNcc, String nomeNcc, String pseudonimoNcc, String nacionalidadeNcc, Date dataNascimentoNcc, String emailNcc, Date dataObitoNcc) {
       this.idAutorNcc = idAutorNcc;
       this.nomeNcc = nomeNcc;
       this.pseudonimoNcc = pseudonimoNcc;
       this.nacionalidadeNcc = nacionalidadeNcc;
       this.dataNascimentoNcc = dataNascimentoNcc;
       this.emailNcc = emailNcc;
       this.dataObitoNcc = dataObitoNcc;
    }
   
     @Id 

    
    @Column(name="idAutorNcc", unique=true, nullable=false)
    public int getIdAutorNcc() {
        return this.idAutorNcc;
    }
    
    public void setIdAutorNcc(int idAutorNcc) {
        this.idAutorNcc = idAutorNcc;
    }

    
    @Column(name="nomeNcc", length=50)
    public String getNomeNcc() {
        return this.nomeNcc;
    }
    
    public void setNomeNcc(String nomeNcc) {
        this.nomeNcc = nomeNcc;
    }

    
    @Column(name="PseudonimoNcc", length=20)
    public String getPseudonimoNcc() {
        return this.pseudonimoNcc;
    }
    
    public void setPseudonimoNcc(String pseudonimoNcc) {
        this.pseudonimoNcc = pseudonimoNcc;
    }

    
    @Column(name="nacionalidadeNcc", length=20)
    public String getNacionalidadeNcc() {
        return this.nacionalidadeNcc;
    }
    
    public void setNacionalidadeNcc(String nacionalidadeNcc) {
        this.nacionalidadeNcc = nacionalidadeNcc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataNascimentoNcc", length=10)
    public Date getDataNascimentoNcc() {
        return this.dataNascimentoNcc;
    }
    
    public void setDataNascimentoNcc(Date dataNascimentoNcc) {
        this.dataNascimentoNcc = dataNascimentoNcc;
    }

    
    @Column(name="emailNcc", length=30)
    public String getEmailNcc() {
        return this.emailNcc;
    }
    
    public void setEmailNcc(String emailNcc) {
        this.emailNcc = emailNcc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataObitoNcc", length=10)
    public Date getDataObitoNcc() {
        return this.dataObitoNcc;
    }
    
    public void setDataObitoNcc(Date dataObitoNcc) {
        this.dataObitoNcc = dataObitoNcc;
    }




}


