package bean;
// Generated 26/09/2025 15:05:32 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClienteNcc generated by hbm2java
 */
@Entity
@Table(name="clienteNcc"
    ,catalog="db_nicole_comelli"
)
public class ClienteNcc  implements java.io.Serializable {


     private int idClienteNcc;
     private String nomeNcc;
     private Date dataNascimentoNcc;
     private String idadeNcc;
     private String cpfNcc;
     private String rgNcc;
     private String ocupacaoNcc;
     private String emailNcc;
     private String telefoneNcc;
     private Date dataCadastroNcc;
     private String ruaNcc;
     private String numeroNcc;
     private String bairroNcc;
     private String cidadeNcc;
     private String cepNcc;
     private String complementoNcc;
     private String ativoNcc;
     private double totalGastoNcc;

    public ClienteNcc() {
    }

	
    public ClienteNcc(int idClienteNcc) {
        this.idClienteNcc = idClienteNcc;
    }
    public ClienteNcc(int idClienteNcc, String nomeNcc, Date dataNascimentoNcc, String idadeNcc, String cpfNcc, String rgNcc, 
            String ocupacaoNcc, String emailNcc, String telefoneNcc, Date dataCadastroNcc, String ruaNcc, String numeroNcc, 
            String bairroNcc, String cidadeNcc, String cepNcc, String complementoNcc, String ativoNcc, double totalGastoNcc) {
       this.idClienteNcc = idClienteNcc;
       this.nomeNcc = nomeNcc;
       this.dataNascimentoNcc = dataNascimentoNcc;
       this.idadeNcc = idadeNcc;
       this.cpfNcc = cpfNcc;
       this.rgNcc = rgNcc;
       this.ocupacaoNcc = ocupacaoNcc;
       this.emailNcc = emailNcc;
       this.telefoneNcc = telefoneNcc;
       this.dataCadastroNcc = dataCadastroNcc;
       this.ruaNcc = ruaNcc;
       this.numeroNcc = numeroNcc;
       this.bairroNcc = bairroNcc;
       this.cidadeNcc = cidadeNcc;
       this.cepNcc = cepNcc;
       this.complementoNcc = complementoNcc;
       this.ativoNcc = ativoNcc;
       this.totalGastoNcc = totalGastoNcc;
    }
   
     @Id 

    
    @Column(name="idClienteNcc", unique=true, nullable=false)
    public int getIdClienteNcc() {
        return this.idClienteNcc;
    }
    
    public void setIdClienteNcc(int idClienteNcc) {
        this.idClienteNcc = idClienteNcc;
    }

    
    @Column(name="nomeNcc", length=50)
    public String getNomeNcc() {
        return this.nomeNcc;
    }
    
    public void setNomeNcc(String nomeNcc) {
        this.nomeNcc = nomeNcc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataNascimentoNcc", length=10)
    public Date getDataNascimentoNcc() {
        return this.dataNascimentoNcc;
    }
    
    public void setDataNascimentoNcc(Date dataNascimentoNcc) {
        this.dataNascimentoNcc = dataNascimentoNcc;
    }

    
    @Column(name="idadeNcc", length=45)
    public String getIdadeNcc() {
        return this.idadeNcc;
    }
    
    public void setIdadeNcc(String idadeNcc) {
        this.idadeNcc = idadeNcc;
    }

    
    @Column(name="cpfNcc", length=15)
    public String getCpfNcc() {
        return this.cpfNcc;
    }
    
    public void setCpfNcc(String cpfNcc) {
        this.cpfNcc = cpfNcc;
    }

    
    @Column(name="rgNcc", length=11)
    public String getRgNcc() {
        return this.rgNcc;
    }
    
    public void setRgNcc(String rgNcc) {
        this.rgNcc = rgNcc;
    }

    
    @Column(name="ocupacaoNcc", length=30)
    public String getOcupacaoNcc() {
        return this.ocupacaoNcc;
    }
    
    public void setOcupacaoNcc(String ocupacaoNcc) {
        this.ocupacaoNcc = ocupacaoNcc;
    }

    
    @Column(name="emailNcc", length=30)
    public String getEmailNcc() {
        return this.emailNcc;
    }
    
    public void setEmailNcc(String emailNcc) {
        this.emailNcc = emailNcc;
    }

    
    @Column(name="telefoneNcc", length=20)
    public String getTelefoneNcc() {
        return this.telefoneNcc;
    }
    
    public void setTelefoneNcc(String telefoneNcc) {
        this.telefoneNcc = telefoneNcc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataCadastroNcc", length=10)
    public Date getDataCadastroNcc() {
        return this.dataCadastroNcc;
    }
    
    public void setDataCadastroNcc(Date dataCadastroNcc) {
        this.dataCadastroNcc = dataCadastroNcc;
    }

    
    @Column(name="ruaNcc", length=30)
    public String getRuaNcc() {
        return this.ruaNcc;
    }
    
    public void setRuaNcc(String ruaNcc) {
        this.ruaNcc = ruaNcc;
    }

    
    @Column(name="numeroNcc", length=4)
    public String getNumeroNcc() {
        return this.numeroNcc;
    }
    
    public void setNumeroNcc(String numeroNcc) {
        this.numeroNcc = numeroNcc;
    }

    
    @Column(name="bairroNcc", length=40)
    public String getBairroNcc() {
        return this.bairroNcc;
    }
    
    public void setBairroNcc(String bairroNcc) {
        this.bairroNcc = bairroNcc;
    }

    
    @Column(name="cidadeNcc", length=50)
    public String getCidadeNcc() {
        return this.cidadeNcc;
    }
    
    public void setCidadeNcc(String cidadeNcc) {
        this.cidadeNcc = cidadeNcc;
    }

    
    @Column(name="cepNcc", length=10)
    public String getCepNcc() {
        return this.cepNcc;
    }
    
    public void setCepNcc(String cepNcc) {
        this.cepNcc = cepNcc;
    }

    
    @Column(name="complementoNcc", length=30)
    public String getComplementoNcc() {
        return this.complementoNcc;
    }
    
    public void setComplementoNcc(String complementoNcc) {
        this.complementoNcc = complementoNcc;
    }

    
    @Column(name="ativoNcc", length=1)
    public String getAtivoNcc() {
        return this.ativoNcc;
    }
    
    public void setAtivoNcc(String ativoNcc) {
        this.ativoNcc = ativoNcc;
    }

    
    @Column(name="totalGastoNcc", precision=10)
    public double getTotalGastoNcc() {
        return this.totalGastoNcc;
    }
    
    public void setTotalGastoNcc(double totalGastoNcc) {
        this.totalGastoNcc = totalGastoNcc;
    }




}


