package bean;
// Generated 26/09/2025 15:05:32 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LivroNcc generated by hbm2java
 */
@Entity
@Table(name="livroNcc"
    ,catalog="db_nicole_comelli"
)
public class LivroNcc  implements java.io.Serializable {


     private int idLivroNcc;
     private String tituloNcc;
     private String numPaginasNcc;
     private String autorNcc;
     private String edicaoNcc;
     private Date dataCadastroNcc;
     private Date dataPublicacaoNcc;

    public LivroNcc() {
    }

	
    public LivroNcc(int idLivroNcc) {
        this.idLivroNcc = idLivroNcc;
    }
    public LivroNcc(int idLivroNcc, String tituloNcc, String numPaginasNcc, String autorNcc, String edicaoNcc, 
            Date dataCadastroNcc, Date dataPublicacaoNcc) {
       this.idLivroNcc = idLivroNcc;
       this.tituloNcc = tituloNcc;
       this.numPaginasNcc = numPaginasNcc;
       this.autorNcc = autorNcc;
       this.edicaoNcc = edicaoNcc;
       this.dataCadastroNcc = dataCadastroNcc;
       this.dataPublicacaoNcc = dataPublicacaoNcc;
    }
   
     @Id 

    
    @Column(name="idLivroNcc", unique=true, nullable=false)
    public int getIdLivroNcc() {
        return this.idLivroNcc;
    }
    
    public void setIdLivroNcc(int idLivroNcc) {
        this.idLivroNcc = idLivroNcc;
    }

    
    @Column(name="tituloNcc", length=50)
    public String getTituloNcc() {
        return this.tituloNcc;
    }
    
    public void setTituloNcc(String tituloNcc) {
        this.tituloNcc = tituloNcc;
    }

    
    @Column(name="numPaginasNcc", length=20)
    public String getNumPaginasNcc() {
        return this.numPaginasNcc;
    }
    
    public void setNumPaginasNcc(String numPaginasNcc) {
        this.numPaginasNcc = numPaginasNcc;
    }

    
    @Column(name="autorNcc", length=50)
    public String getAutorNcc() {
        return this.autorNcc;
    }
    
    public void setAutorNcc(String autorNcc) {
        this.autorNcc = autorNcc;
    }

    
    @Column(name="edicaoNcc", length=4)
    public String getEdicaoNcc() {
        return this.edicaoNcc;
    }
    
    public void setEdicaoNcc(String edicaoNcc) {
        this.edicaoNcc = edicaoNcc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataCadastroNcc", length=10)
    public Date getDataCadastroNcc() {
        return this.dataCadastroNcc;
    }
    
    public void setDataCadastroNcc(Date dataCadastroNcc) {
        this.dataCadastroNcc = dataCadastroNcc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataPublicacaoNcc", length=10)
    public Date getDataPublicacaoNcc() {
        return this.dataPublicacaoNcc;
    }
    
    public void setDataPublicacaoNcc(Date dataPublicacaoNcc) {
        this.dataPublicacaoNcc = dataPublicacaoNcc;
    }




}


