package bean;
// Generated 26/09/2025 15:05:32 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UsuariosNcc generated by hbm2java
 */
@Entity
@Table(name="usuariosNcc"
    ,catalog="db_nicole_comelli"
)
public class UsuariosNcc  implements java.io.Serializable {


     private int idUsuariosNcc;
     private String nomeNcc;
     private String apelidoNcc;
     private String cpfNcc;
     private Date dataNascimentoNcc;
     private String senhaNcc;
     private int nivelNcc;
     private String ativoNcc;

    public UsuariosNcc() {
    }

	
    public UsuariosNcc(int idUsuariosNcc) {
        this.idUsuariosNcc = idUsuariosNcc;
    }
    public UsuariosNcc(int idUsuariosNcc, String nomeNcc, String apelidoNcc, String cpfNcc, Date dataNascimentoNcc, 
            String senhaNcc, int nivelNcc, String ativoNcc) {
       this.idUsuariosNcc = idUsuariosNcc;
       this.nomeNcc = nomeNcc;
       this.apelidoNcc = apelidoNcc;
       this.cpfNcc = cpfNcc;
       this.dataNascimentoNcc = dataNascimentoNcc;
       this.senhaNcc = senhaNcc;
       this.nivelNcc = nivelNcc;
       this.ativoNcc = ativoNcc;
    }
   
     @Id 

    
    @Column(name="idUsuariosNcc", unique=true, nullable=false)
    public int getIdUsuariosNcc() {
        return this.idUsuariosNcc;
    }
    
    public void setIdUsuariosNcc(int idUsuariosNcc) {
        this.idUsuariosNcc = idUsuariosNcc;
    }

    
    @Column(name="nomeNcc", length=50)
    public String getNomeNcc() {
        return this.nomeNcc;
    }
    
    public void setNomeNcc(String nomeNcc) {
        this.nomeNcc = nomeNcc;
    }

    
    @Column(name="apelidoNcc", length=20)
    public String getApelidoNcc() {
        return this.apelidoNcc;
    }
    
    public void setApelidoNcc(String apelidoNcc) {
        this.apelidoNcc = apelidoNcc;
    }

    
    @Column(name="cpfNcc", length=15)
    public String getCpfNcc() {
        return this.cpfNcc;
    }
    
    public void setCpfNcc(String cpfNcc) {
        this.cpfNcc = cpfNcc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataNascimentoNcc", length=10)
    public Date getDataNascimentoNcc() {
        return this.dataNascimentoNcc;
    }
    
    public void setDataNascimentoNcc(Date dataNascimentoNcc) {
        this.dataNascimentoNcc = dataNascimentoNcc;
    }

    
    @Column(name="senhaNcc", length=20)
    public String getSenhaNcc() {
        return this.senhaNcc;
    }
    
    public void setSenhaNcc(String senhaNcc) {
        this.senhaNcc = senhaNcc;
    }

    
    @Column(name="nivelNcc")
    public int getNivelNcc() {
        return this.nivelNcc;
    }
    
    public void setNivelNcc(int nivelNcc) {
        this.nivelNcc = nivelNcc;
    }

    
    @Column(name="ativoNcc", length=1)
    public String getAtivoNcc() {
        return this.ativoNcc;
    }
    
    public void setAtivoNcc(String ativoNcc) {
        this.ativoNcc = ativoNcc;
    }




}


