package bean;
// Generated 26/09/2025 15:05:32 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VendasProdutosNcc generated by hbm2java
 */
@Entity
@Table(name="vendasProdutosNcc"
    ,catalog="db_nicole_comelli"
)
public class VendasProdutosNcc  implements java.io.Serializable {


     private int idVendasProdutosNcc;
     private LivroNcc livroNcc;
     private VendasNcc vendasNcc;
     private int quantidadeNcc;
     private double valorUnitarioNcc;

    public VendasProdutosNcc() {
    }

	
    public VendasProdutosNcc(int idVendasProdutosNcc) {
        this.idVendasProdutosNcc = idVendasProdutosNcc;
    }
    public VendasProdutosNcc(int idVendasProdutosNcc, LivroNcc livroNcc, VendasNcc vendasNcc, int quantidadeNcc, 
            double valorUnitarioNcc) {
       this.idVendasProdutosNcc = idVendasProdutosNcc;
       this.livroNcc = livroNcc;
       this.vendasNcc = vendasNcc;
       this.quantidadeNcc = quantidadeNcc;
       this.valorUnitarioNcc = valorUnitarioNcc;
    }
   
     @Id 

    
    @Column(name="idVendasProdutosNcc", unique=true, nullable=false)
    public int getIdVendasProdutosNcc() {
        return this.idVendasProdutosNcc;
    }
    
    public void setIdVendasProdutosNcc(int idVendasProdutosNcc) {
        this.idVendasProdutosNcc = idVendasProdutosNcc;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkLivroNcc")
    public LivroNcc getLivroNcc() {
        return this.livroNcc;
    }
    
    public void setLivroNcc(LivroNcc livroNcc) {
        this.livroNcc = livroNcc;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkVendasNcc")
    public VendasNcc getVendasNcc() {
        return this.vendasNcc;
    }
    
    public void setVendasNcc(VendasNcc vendasNcc) {
        this.vendasNcc = vendasNcc;
    }

    
    @Column(name="quantidadeNcc")
    public int getQuantidadeNcc() {
        return this.quantidadeNcc;
    }
    
    public void setQuantidadeNcc(int quantidadeNcc) {
        this.quantidadeNcc = quantidadeNcc;
    }

    
    @Column(name="valorUnitarioNcc", precision=10)
    public double getValorUnitarioNcc() {
        return this.valorUnitarioNcc;
    }
    
    public void setValorUnitarioNcc(double valorUnitarioNcc) {
        this.valorUnitarioNcc = valorUnitarioNcc;
    }




}


