package bean;
// Generated 26/09/2025 15:05:32 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendedorNcc generated by hbm2java
 */
@Entity
@Table(name="vendedorNcc"
    ,catalog="db_nicole_comelli"
)
public class VendedorNcc  implements java.io.Serializable {


     private int idVendedorNcc;
     private String nomeNcc;
     private String apelidoNcc;
     private String cpfNcc;
     private Date dataNascimentoNcc;
     private String emailNcc;
     private String telefoneNcc;

    public VendedorNcc() {
    }

	
    public VendedorNcc(int idVendedorNcc) {
        this.idVendedorNcc = idVendedorNcc;
    }
    public VendedorNcc(int idVendedorNcc, String nomeNcc, String apelidoNcc, String cpfNcc, Date dataNascimentoNcc,
            String emailNcc, String telefoneNcc) {
       this.idVendedorNcc = idVendedorNcc;
       this.nomeNcc = nomeNcc;
       this.apelidoNcc = apelidoNcc;
       this.cpfNcc = cpfNcc;
       this.dataNascimentoNcc = dataNascimentoNcc;
       this.emailNcc = emailNcc;
       this.telefoneNcc = telefoneNcc;
    }
   
     @Id 

    
    @Column(name="idVendedorNcc", unique=true, nullable=false)
    public int getIdVendedorNcc() {
        return this.idVendedorNcc;
    }
    
    public void setIdVendedorNcc(int idVendedorNcc) {
        this.idVendedorNcc = idVendedorNcc;
    }

    
    @Column(name="nomeNcc", length=50)
    public String getNomeNcc() {
        return this.nomeNcc;
    }
    
    public void setNomeNcc(String nomeNcc) {
        this.nomeNcc = nomeNcc;
    }

    
    @Column(name="apelidoNcc", length=20)
    public String getApelidoNcc() {
        return this.apelidoNcc;
    }
    
    public void setApelidoNcc(String apelidoNcc) {
        this.apelidoNcc = apelidoNcc;
    }

    
    @Column(name="cpfNcc", length=11)
    public String getCpfNcc() {
        return this.cpfNcc;
    }
    
    public void setCpfNcc(String cpfNcc) {
        this.cpfNcc = cpfNcc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataNascimentoNcc", length=10)
    public Date getDataNascimentoNcc() {
        return this.dataNascimentoNcc;
    }
    
    public void setDataNascimentoNcc(Date dataNascimentoNcc) {
        this.dataNascimentoNcc = dataNascimentoNcc;
    }

    
    @Column(name="emailNcc", length=30)
    public String getEmailNcc() {
        return this.emailNcc;
    }
    
    public void setEmailNcc(String emailNcc) {
        this.emailNcc = emailNcc;
    }

    
    @Column(name="telefoneNcc", length=12)
    public String getTelefoneNcc() {
        return this.telefoneNcc;
    }
    
    public void setTelefoneNcc(String telefoneNcc) {
        this.telefoneNcc = telefoneNcc;
    }


}


