package bean;
// Generated 26/09/2025 15:05:32 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendasNcc generated by hbm2java
 */
@Entity
@Table(name="vendasNcc"
    ,catalog="db_nicole_comelli"
)
public class VendasNcc  implements java.io.Serializable {


     private int idVendasNcc;
     private ClienteNcc clienteNcc;
     private VendedorNcc vendedorNcc;
     private Date dataVendaNcc;
     private double totalNcc;
     

    public VendasNcc() {
    }

	
    public VendasNcc(int idVendasNcc) {
        this.idVendasNcc = idVendasNcc;
    }
    public VendasNcc(int idVendasNcc, ClienteNcc clienteNcc, VendedorNcc vendedorNcc, Date dataVendaNcc, double totalNcc) {
       this.idVendasNcc = idVendasNcc;
       this.clienteNcc = clienteNcc;
       this.vendedorNcc = vendedorNcc;
       this.dataVendaNcc = dataVendaNcc;
       this.totalNcc = totalNcc;
    }
   
     @Id 

    
    @Column(name="idVendasNcc", unique=true, nullable=false)
    public int getIdVendasNcc() {
        return this.idVendasNcc;
    }
    
    public void setIdVendasNcc(int idVendasNcc) {
        this.idVendasNcc = idVendasNcc;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkClienteNcc")
    public ClienteNcc getClienteNcc() {
        return this.clienteNcc;
    }
    
    public void setClienteNcc(ClienteNcc clienteNcc) {
        this.clienteNcc = clienteNcc;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkVendedorNcc")
    public VendedorNcc getVendedorNcc() {
        return this.vendedorNcc;
    }
    
    public void setVendedorNcc(VendedorNcc vendedorNcc) {
        this.vendedorNcc = vendedorNcc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataVendaNcc", length=10)
    public Date getDataVendaNcc() {
        return this.dataVendaNcc;
    }
    
    public void setDataVendaNcc(Date dataVendaNcc) {
        this.dataVendaNcc = dataVendaNcc;
    }

    
    @Column(name="totalNcc", precision=10)
    public double getTotalNcc() {
        return this.totalNcc;
    }
    
    public void setTotalNcc(double totalNcc) {
        this.totalNcc = totalNcc;
    }


}


